### ISSUE TITLE
ImportError: cannot import name websocket on ESP32

### ISSUE THREAD

**Issue by rdagger** [BetaRavener/upy-websocket-server#1]
When I run the websocket.py I get the following error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "websocket.py", line 1, in <module>
>   File "ws_connection.py", line 2, in <module>
> ImportError: cannot import name websocket

Looks like websocket.py imports from ws_connection.py which then tries to import websocket from websocket.py which doesn't contain a class called websocket.  Not sure if it matters, but I'm using an ESP32 with latest firmware.

**Comment by BetaRavener** [comment]
Hi, thanks for reporting it. I look into it, but bear in mind that ESP32 is new device and maybe not all of the micropython functionality that runs on ESP8266 may be available already. Websockets may not be implemented yet for ESP32 (although if the WebREPL is working, they should be).
**EDIT:** First thing, try to rename `websocket.py` that you downloaded from here to something else. It shouldn't matter how it's called. I just noticed that I named the filed same as library from where it should import the class.

**Comment by rdagger** [comment]
I did try renaming and it didn't help.  WebREPL is not implemented for the ESP32 as far as I know and there is no module named websocket on the latest firmware.
Thanks.

**Comment by goatchurchprime** [comment]
In particular, your main module is called "websocket.py" which is pretty confusing if there is an outside library also called websocket.  

I mean it's inconsistent if the line at the top of websocket.py is:
    from ws_connection import ClientClosedError
and it's supposed to import from ws_connection.py

but the line at the top of ws_connection.py is
    from websocket import websocket
and it's NOT supposed to import from websocket.py



ws_connection

**Comment by BetaRavener** [comment]
Sorry, this was already changed but forgot to push. It should be clear now which is which.

**Comment by BetaRavener** [comment]
Should be resolved.
