### ISSUE TITLE
State is always 3

### ISSUE THREAD

**Issue by Piechota** [BetaRavener/upy-websocket-server#13]
I am running webSocket server on esp8266.
On browser I connected to it with javascript.
State of webSocket on esp8266 is always 3, so _check_socket_state closes it.
When closing tab with website, state changes to 4 which isn't listed here:
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState 

When _check_socket_state check to 4 it doesn't react to closing webSocket in javascript.

It happens also with websocket_demo.py

**Comment by ryaowe** [comment]
It looks like the "PEER_CLOSED" state was changed from 3 to 4 since this was last udpated: https://github.com/micropython/micropython/commit/29da9f06709df77d15437b67db5978ecafcccaef
