### ISSUE TITLE
Change socket state check to state == 4

### ISSUE THREAD

**Issue by vlad2305m** [BetaRavener/upy-websocket-server#15]
Idk what the hell is going on, but this simple change seems to stop the socket from closing after the first message
(Saw it in https://github.com/AdrianCX/crawlspacebot/commit/7ba06ad1dfcd8eaea91d77a2eb30e69efb4ee7fe)

**Comment by BetaRavener** [comment]
Looks to be same issue as #13, hence this seems confirmed by multiple people. Comment in that issue also gives potential explanation. I'll update the code.

**Comment by BetaRavener** [comment]
Hope the issue will be fixed now, thanks for reporting. Feel free to reopen or create a new issue if the behavior is still not as expected.
