### ISSUE TITLE
Load couple files via server.

### ISSUE THREAD

**Issue by plugowski** [BetaRavener/upy-websocket-server#4]
Is it possible to load couple files via that solution? Now I'm able to load only main file like index.html, but what if I want to load extra stylesheets and images from ESP? Is it possible?

**Comment by BetaRavener** [comment]
I wouldn't recommend making things too complicated, you could put some CSS directly into HTML. You could probably serve multiple files as they are needed, but this is currently not supported.

If I were doing something like this, I would put only critical functionality on the ESP that allows you to do what you need, and everything else that's just eyecandy could be pulled from external sites over internet. So basically you would load the HTML with some javascript from ESP, but that webpage would reference images from some external server. If you don't have internet connection on client device, you would still be able to control the device, but without fancy styles.

**Comment by plugowski** [comment]
The main problem is no internet connection when I connect to ESP and I have an idea to create web-based interface for my project. It will be the first stage because in the future of course I want to write my own app for iOS.

**Comment by BetaRavener** [comment]
Well, you'd need to change `ws_server.py` file, specifically `_accept_connection` method. There, you would put code that would handle request for each individual file, depending on the URL. At least I think that's how it works :)

**Comment by BetaRavener** [comment]
Hey, going to close this one for now. 

If you successfully implemented this, it would be great if you could post a link to repository :) If you are still trying to do so, I can give you (or anyone that finds this) some more leads. After accepting new connection, you want to read the request. Its contents are currently ignored and for each request `_serve_page` send the same file no matter what. Instead, after reading the request (which is HTTP protocol), you want to extract URL address, which is right after the HTTP method (in our case should be always `GET`). Some more details [here](https://www.w3.org/Protocols/HTTP/Request.html). After trimming the server name from the URL, you're left with the name of requested resource (==file). This string decides what file gets served. You could parameterize `_serve_page` to take a name of a file that gets served as an argument, and just pass it the extracted string. There might be some problems with binary files such as images that you want to deal with. Currently the file is opened in text mode with `"r"` argument and sent by lines. You'd probably want to open it in binary mode `"rb"` and use buffer of some length (say 100 bytes) to send file in chunks so that it doesn't consume all of the ESP's memory. Happy implementing! :)

**Comment by plugowski** [comment]
I tried to implement it, but I stucked in socket.recv() this method looks like it stuck and doesn't do anything... Maybe you can check what I'm doing wrong :)

https://github.com/plugowski/micropython-utils/blob/uwebsocket/uwebsocket/__init__.py

**Comment by BetaRavener** [comment]
That code looks good to me, What I realized is that `websocket_helper.server_handshake` is probably reading something from the socket to determine, if it is websocket connection. Code for that thing is [here](https://github.com/micropython/webrepl/blob/master/websocket_helper.py#L13). You would need to copy and modify this function, to return at least the HTTP method and resource string in case it finds out, that the connection is not websocket.

**Comment by plugowski** [comment]
@BetaRavener thank you for suggestion. Propably it was a problem, so I call recv() couple lines before and it works fine! I Also added some mime_types generated in header, and server reply with files in located in web_dir (maybe I add an option to change in fly that directory), I try to serve even big images and ESP32 can do that without any chunks :)

I've pushed new code.

**Comment by BetaRavener** [comment]
Good job! :) You kind of hacked around that `server_handshake` but looking at the code and an [example of a handshake](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers), things should work fine as long as you don't read too much from the socket (there should be at least one line left before `Sec-WebSocket-Key` field).

**Comment by Cosmat** [comment]
Hello! Whether prompt please it is possible to connect with html the page given out by yours esp the server separate files in css and js.  I tyr but not works(((...

**Comment by BetaRavener** [comment]
It's not possible whit what you can find in this repository but @plugowski implemented this in his [micropython-utils](https://github.com/plugowski/micropython-utils/blob/uwebsocket/uwebsocket/__init__.py). With his permission, I could add those changes once I have some spare time. So @plugowski either let me know if you'd like to see you work merged here, or you can create pull request and we will collaborate on this.

**Comment by Cosmat** [comment]
I very much ask you to implement in your script the ability to connect external js and css files. As I think this opportunity would make your project more universal, flexible, you expanded its possible implementation.
I'm from Russia and my English is very bad. I use Google translator to write this message. Thank you for the already existing code for this project and I still hope you will find the time to add the connectivity to the external js and css files.

**Comment by BetaRavener** [comment]
@Cosmat Ok, I will try to add it to the code. However, I can't promise you when this will happen, for next month I will be very busy studying for my final exams. So it might take more than a month, unless I happen to have some spare time. 

If you can't wait, again I suggest looking at the linked repository. Or if the device that displays webpage is connected to internet, put css and js files on server and link them from the HTML.

**Comment by Cosmat** [comment]
Thank you so much for your work and this project. As for the time you need for a supplement, about which I asked you, please do not worry. Just know that someone will wait for this result).
With regard to the implementation of connecting the  files via the Internet, then this option is not suitable for me. My device according to the plan should be fully operational, remaining autonomous.
And again I tell you many thanks for your work.
