### ISSUE TITLE
How send any data to client?

### ISSUE THREAD

**Issue by Cosmat** [BetaRavener/upy-websocket-server#6]
How send any data to client? Plz )))

**Comment by BetaRavener** [comment]
What do you mean? Sending data via websocket? There's a demo implementation in [`websocket_demo.py` ](https://github.com/BetaRavener/upy-websocket-server/blob/master/websocket_demo.py#L18)that will send "Hello World" when you run on ESP and connect with client. So basically from the linked file: `self.connection.write(data)`. Try out the linked demo file and you will hopefully get an idea how it works.

**Comment by Cosmat** [comment]
Oh thanks. I forget it). Sorry...)) Im working with client so long. Trying using Vue with websockets. 
And i want again say to you GREAT THANKS for this your code!!!

**Comment by BetaRavener** [comment]
You're welcome. :) Good luck, I'll leave this open for today if you have more questions.
